server:
  port: ":2020"               # 以前的项目是在 2020 端口开放给前端的
ssh:
  Host: xx.xxx.xx.xxx         # 云服务器公网 ip
  User: root                  # 云服务器 ssh 时的用户名，此 root 非彼 root
  Port: 22                    # ssh 用 22 端口
  Type: "KEY"                 # 如果用密钥登陆的话才有用，忽视
  Password: xxxxxxxxxxx       # 云服务器密码
  KeyFile: "~/.ssh/id_rsa"    # 如果用密钥登陆的话才有用，忽视

db:                           # 后端 mysql
  hostname: xx.xxx.xx.xx      
  port: 3307                  
  username: xxxx              
  password: xxxxxx            
  dbname: xxxxxx

syncdb:
  hostname: xx.xxx.xx.xx      # ssh 连接后开发环境变成主机，此时直接用环回自检地址表示数据库IP地址
  port: 3307                  # 同理端口也是 3306
  username: root              # 云服务器上的 sql 用户名，已经不是本地的用户了
  password: xxxxxx            # 登录密码
  dbname: xxxxxx              # 这是以前的项目的数据库名